pysal/momepy

- momepy/connectivity.py
- momepy/datasets/__init__.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/intensity.py
- momepy/shape.py
- momepy/utils.py
- tests/test_distribution.py
- tests/test_shape.py
Cleaning the code based on codefactor reports.
> MAINT: Code cleaning

- momepy/dimension.py
- momepy/shape.py
- tests/test_dimension.py
- tests/test_shape.py
> TST: Tests coverage

- momepy/dimension.py
- momepy/distribution.py
- momepy/intensity.py
Added checks for functions using spatial_weights to ensure that iloc == loc.
Closes #6
> BUG: added checks of index when spatial weights are used

- momepy/distribution.py
- tests/test_distribution.py
Added test unit for distribution. During that I eliminated couple of minor bugs in the actual code.
> Test distribution

- momepy/intensity.py
- tests/test_intensity.py
Test unit for intensity and fixes within intensity.
> TST: intensity and some fixes

- momepy/diversity.py
- momepy/elements.py
- momepy/utils.py
- tests/test_dimension.py
- tests/test_utils.py
Couple of bug fixes. Adding compatibility with mapclassify 2.1.1 for Simpson's index, fixing incorrect handling of NaN values.
> BUGS: mapclassify, NaNs in limit_range and get_node_ID

- momepy/utils.py
Changed the name of variable, even though original uID does not have any value after `preprocess`.
> BUG: Avoid overwriting 'uID' in preprocess()

- momepy/utils.py
`preprocess` has left columns of former index. Now it returns clean gdf.
> BUG: preprocess did not drop index

- momepy/elements.py
First small step in refactoring `tessellation`.
> REF: use _get_centre in tessellation

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/intensity.py
- momepy/shape.py
Pass original index to Series with resulting values to ensure correct mapping.
> BUG: Ensure that series has corrrect index

- momepy/elements.py
- tests/test_elements.py
Continuation of #40 refactor of tessellation internals.
> PERF: refactor _split_lines to return lines of set distance

- README.md
- docs/index.rst
- docs/install.rst
momepy is on both PyPI and Conda-forge. Updated instructions accordingly.
> DOC: conda-forge install instructions

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/intensity.py
Some functions were using append to the list of neighbours which in fact appended the value to spatial weights matrix itself.
> BUG: appendind to spatial weights

- momepy/dimension.py
- momepy/utils.py
See https://github.com/geopandas/geopandas/issues/1100. Using workaround for now.
> BUG: fix for gpd 0.6 GeoSeries.any()

- momepy/dimension.py
- tests/test_dimension.py
mean_character changes to average_character and allows median and mode on top of mean.
> ENH: allow mode in average

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/intensity.py
- momepy/utils.py
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_diversity.py
- tests/test_intensity.py
- tests/test_utils.py
Change `Queen_higher` to `sw_high` to make explicit that it can make higher order of anything. Allow rook.
> API: Queen_higher -> sw_high

- docs/api.rst
- docs/conf.py
- docs/environment.yml
Autoload version to docs. Fix link to guide.
> DOC: Version

- momepy/graph.py
- tests/test_graph.py
Generating subgraph might be a time consuming activity. If we want to use the same subgraph for more characters, ``subgraph()`` allows this by generating subgraph and then analysing it using selected options.
> ENH: subgraph() to calculate all chars based on subgraph at once

- momepy/__init__.py
- momepy/datasets/__init__.py
- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/graph.py
- momepy/intensity.py
- momepy/shape.py
- momepy/utils.py
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_diversity.py
- tests/test_elements.py
- tests/test_graph.py
- tests/test_intensity.py
- tests/test_shape.py
- tests/test_utils.py
Use [black](https://github.com/psf/black) for code formatting for coherency.
> STYLE: blacked code

- momepy/graph.py
- momepy/utils.py
- tests/test_graph.py
- tests/test_utils.py
`gdf_to_nx` is now able to generate both primal and dual graph based on the street network. `nx_to_gdf` can turn both back to geodataframe, while for dual only lines are possible. 
+ some minor changes to graph algorithms
> ENH: Dual graph, minor graph changes

- momepy/distribution.py
- momepy/elements.py
- momepy/utils.py
- fixes for sindex
- network_false_nodes explode in the end
> BUG: minor fixes

- momepy/diversity.py
- tests/test_diversity.py
Theil of np.zeros gives nan instead of 0.
> BUG: Handle Theil of zeros

- docs/api.rst
- docs/conf.py
- docs/environment.yml
- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/intensity.py
- momepy/shape.py
- momepy/utils.py
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_diversity.py
- tests/test_intensity.py
- tests/test_shape.py
- tests/test_utils.py
All functions measuring characters on gdf are now classes. This change enables better extensibility of each of them and provides a way of storing all used attributes and data.
> API: classes 

- docs/api.rst
- momepy/elements.py
- tests/test_elements.py
- tests/test_intensity.py
Make Tessellation and Blocks classes. Make queen_higher method of Tessellation.
> API: tessellation and blocks as classes

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/graph.py
- momepy/intensity.py
- momepy/shape.py
- momepy/utils.py
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_diversity.py
- tests/test_elements.py
- tests/test_graph.py
- tests/test_intensity.py
- tests/test_shape.py
- tests/test_utils.py
Added `__all__` where applicable. At the same time, imports were ordered using `isort`.
> MAINT: add __all__

- docs/api.rst
- momepy/graph.py
- tests/test_graph.py
Add local betweenness (nodes only) and local straightness
> ENH: local straightness & betweenness centrality

- momepy/dimension.py
- tests/test_dimension.py
> BUG: StreetProfile did not run without height

- momepy/utils.py
`G.node` is deprecated -> `G.nodes`
> BUG: fix for networkx2.4

- momepy/shape.py
- tests/test_shape.py
Fractal Dimension taken from Hermosilla et al (2014) is not correct. This PR fixes it based on FRAGSTATS.
> BUG: fix FractalDimension formula

- momepy/intensity.py
Fixes #109 
Avoid `SettingWithCopyWarning` in `AreaRatio`.
> BUG: `SettingWithCopyWarning` in AreaRatio

- momepy/elements.py
- tests/test_elements.py
Raises ValueError is block ID is already present in gdf.
> ENH: check block_id in Blocks

- .coveragerc
- docs/conf.py
- docs/environment.yml
- momepy/elements.py
- setup.cfg
This should make the docs environment much more lighter. We should not face memory or time issue on readthedocs anymore.
> DOC: use mock for rtd

- README.md
- docs/contributing.rst
- docs/index.rst
Update contributing guidelines to reflect migration of guide to separate repository.
> DOC: update contributing guidelines

- README.md
- docs/index.rst
Add links to JOSS and BibTeX entry to Readme and docs.
> DOC: citing instructions (JOSS)

- CHANGELOG.md
> RLS: 0.1.1 changelog

- momepy/utils.py
Implement `tolerance` and `precision` for `network_false_nodes()` as it sometimes caused issues due to imprecision of floating point. It is slower now, due to `buffer()`, but should be more reliable.
> BUG: float precision errors in network_false_nodes

- ci/travis/latest-mc.yaml
> CI: unpin libpysal

- CITATION.md
- LICENSE
Add CITATION file, update year
> DOC: Citation, year

- momepy/elements.py
> BUG: accidental 'rtd' print

- momepy/shape.py
- tests/test_shape.py
Polygon Z support for circular buildings
> BUG: CentroidCorner may fail for Polygon Z

- momepy/dimension.py
- momepy/distribution.py
- momepy/shape.py
Refactor to eliminate some unnecessary loops and make use of future pygeos backend of geopandas.
> REF: vectorize using numpy and prepare for pygeos

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/intensity.py
- momepy/shape.py
- momepy/utils.py
- tests/test_distribution.py
Several performance improvements. Vectorization, effective iterations.
> ENH: Performance improvements

- momepy/distribution.py
- tests/test_distribution.py
`Orientation` now supports LineString geometry as well.
> ENH: Orientation for LineString geometry

- docs/api.rst
- momepy/diversity.py
- tests/test_diversity.py
Add [Shannon index of diversity](https://en.wikipedia.org/wiki/Diversity_index#Shannon_index).
> ENH: Shannon index

- docs/api.rst
- momepy/diversity.py
- tests/test_diversity.py
Added support of categorical values in `Simpson` and `Shannon`. New class `Unique` measuring number of unique values within a set neighbourhood.
> ENH: Diversity of categorical values

- docs/api.rst
- momepy/elements.py
- momepy/utils.py
- tests/test_distribution.py
- tests/test_utils.py
Add a new function to check input of tessellation for possible issue before doing the tessellation itself. Often happens that tessellation is generated with errors which could have been catched sooner.
> ENH: CheckTessellationInput

- momepy/weights.py
> BUG: DistanceBand memory issue

- docs/user_guide/elements/tessellation.ipynb
- momepy/utils.py
Allow specification of `compactness` and number of loops in `preprocess`.
> ENH: options for preprocess

- momepy/shape.py
- tests/test_shape.py
I added a condition for multi-polygon geometries
> ENH: Fixed squareness for non-Polygon geom types

- momepy/distribution.py
- tests/test_distribution.py
Vectorized operations and query_bulk. I have also caught a bug in master.
Benchmark from 101.348ms to 5.04±0.4ms.
> PERF: refactor NeighboringStreetOrientationDeviation

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/graph.py
- momepy/intensity.py
- momepy/shape.py
- momepy/utils.py
Added `verbose` keyword to functions using tqdm and printing steps, so this can be controlled and silenced.
> ENH: allow specification of verbosity

- momepy/utils.py
Minor cleanup. I have added verbose option to control `tqdm` (will add to other functions as well).
> CLN: network_false_nodes cleanup, verbose option

- momepy/shape.py
Clean-up of `CircularCompactness`.
The algorithm has been rewritten as a part of [Urban Grammar AI research project](https://urbangrammarai.github.io).
> ENH: faster circular compactness

- momepy/elements.py
- tests/test_elements.py
Performance-focused refactoring of `Tessellation` algorithm using some pygeos magic.
The algorithm has been rewritten as a part of [Urban Grammar AI research project](https://urbangrammarai.github.io).
> REF: pygeos-based Tessellation

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/intensity.py
- momepy/shape.py
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_diversity.py
Various speedups and addition of new `Percentiles` class.
The algorithms have been written as a part of [Urban Grammar AI research project](https://urbangrammarai.github.io).
> ENH: speedups, Percentiles

- .pylintrc
- docs/api.rst
- momepy/elements.py
- tests/test_elements.py
Adding a function to generate enclosures based on set barriers. Will be added to the user guide later together with enclosed tessellation.
The algorithm has been written as a part of [Urban Grammar AI research project](https://urbangrammarai.github.io).
> ENH: add enclosures function

- docs/api.rst
- momepy/preprocessing.py
- tests/test_preprocess.py
Extend lines to itself or specified target
The algorithm has been written as a part of [Urban Grammar AI research project](https://urbangrammarai.github.io).
> ENH: extend_lines

- momepy/distribution.py
- momepy/intensity.py
Minor adaptations to make it easier to work with the non-matching spatial unit and buildings (i.e. ET and buildings).
> ENH: adapt code for ET

- momepy/utils.py
- tests/test_utils.py
> ENH: handle NaNs in limit_range

- docs/api.rst
- docs/bibtex.json
- momepy/distribution.py
- tests/test_distribution.py
Closes #203
Allows calculation of shared walls in meters instead of ratio.
> ENH: SharedWalls length

- momepy/utils.py
- tests/test_utils.py
Allow specification of graph type (`Graph`, `DiGraph`, `MultiGraph`, MutliDiGraph`) and whether to compute angles in dual graphs.
Both functions are also refactored so it should also provide significant performance gain.
> ENH: more options in converting to networkx graphs

- ci/envs/stable.yaml
- docs/install.rst
- momepy/diversity.py
- tests/test_diversity.py
> REF: use mapclassify.classify

- momepy/dimension.py
- tests/test_dimension.py
> BUG: fix infinity in StreetProfile

- momepy/elements.py
- momepy/intensity.py
- momepy/preprocessing.py
> BUG: avoid string "geometry"

- ci/envs/stable.yaml
- momepy/elements.py
Closes #265 
I am also removing dask from `stable` env to check this case.
> BUG: UnboundLocalError: local variable 'cpu_count' referenced before assignment 

- momepy/diversity.py
- tests/test_diversity.py
> ENH: distance decay in Percentiles

- momepy/elements.py
- tests/test_elements.py
> BUG: Tessellation error on non-standard enclosures

- momepy/elements.py
- tests/test_elements.py
> ENH: catch geographic CRS in Tessellation

- momepy/elements.py
- tests/test_elements.py
> ENH: support shapely polygon as enclosures limit

- ci/envs/stable.yaml
- momepy/distribution.py
- momepy/elements.py
- momepy/intensity.py
- momepy/preprocessing.py
- tests/test_coins.py
- tests/test_distribution.py
- tests/test_intensity.py
- tests/test_preprocess.py
- tests/test_utils.py
Attempt to minimise warnings coming from different parts of momepy due to geopandas 0.10 and any other cause.
Closes #309
> REF/TST: minimise warnings

- LICENSE
- README.md
- docs/conf.py
- setup.py
> relicense under BSD

- .github/workflows/tests.yaml
- ci/envs/310-dev.yaml
- ci/envs/310-latest.yaml
- ci/envs/37-minimal.yaml
- ci/envs/38-latest.yaml
- ci/envs/39-latest.yaml
- momepy/elements.py
- setup.py
Expand CI matrix to cover 1) minimal supported versions, 2) all relevant Python versions.
> TST: redo CI matrix

- momepy/shape.py
- tests/test_shape.py
Closes #329
This reminded me how much I actually hate myself for the design of these classes and the need for #308.
> BUG: fix FormFactor

- .github/workflows/tests.yaml
- ci/envs/310-dev.yaml
- ci/envs/310-latest.yaml
- ci/envs/37-minimal.yaml
- ci/envs/38-latest.yaml
- ci/envs/39-latest.yaml
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_intensity.py
xref: pysal/spopt#211, pysal/spaghetti#661
> pytest-xdist for multicore CI

- momepy/shape.py
Added heights to parameters for FormFactor Issue #355
> DOC: add heights to parameters for FormFactor

- .github/workflows/tests.yaml
- ci/envs/310-dev.yaml
- ci/envs/310-latest.yaml
- ci/envs/38-minimal.yaml
- ci/envs/39-latest.yaml
> revert to single core CI

- momepy/elements.py
- momepy/preprocessing.py
Closes #383 
This is all that showed up when running tests.
> REF: replace append with concat

- momepy/diversity.py
- momepy/utils.py
Addressing #386 and martinfleis/sdss22-workshop#8.
> address numpy.nanpercentile warning

- momepy/dimension.py
Address #388 & xref https://github.com/martinfleis/sdss22-workshop/issues/8
> handle scenarios leading to dimensions.StreetProfile() warnings

- momepy/dimension.py
- momepy/diversity.py
- tests/test_elements.py
> Fix various warnings

- tests/test_dimension.py
- tests/test_diversity.py
- tests/test_intensity.py
- tests/test_shape.py
> standardize pytest.approx() in testing files

- .coveragerc
- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- ci/envs/310-dev.yaml
- ci/envs/310-latest.yaml
- ci/envs/38-minimal.yaml
- ci/envs/39-latest.yaml
- environment.yml
- requirements.txt
Closes #401 and other minor housekeeping updates.
> Run user guide tests with Python 3.10

- asv.conf.json
> remove pygeos duplicate

- ci/envs/test_user_guide.sh
Follow up on #393. I forgot to fix CI to get those notebooks tested after I moved them.
> CI: test preprocessing part of user guide

- momepy/elements.py
Minor spelling and punctuation update in `elements.Blocks`.
> minor spelling and punctuation update

- momepy/elements.py
- tests/test_elements.py
Closes #408 
I should probably add a test checking this case...
> BUG: get_network_ratio non-interescting joins fix

- .pre-commit-config.yaml
- benchmarks/bench_dimension.py
- benchmarks/bench_distribution.py
- benchmarks/bench_diversity.py
- benchmarks/bench_elements.py
- benchmarks/bench_graph.py
- benchmarks/bench_intensity.py
- benchmarks/bench_shape.py
- benchmarks/bench_utils.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/intensity.py
- momepy/preprocessing.py
- momepy/utils.py
- setup.cfg
- setup.py
- tests/test_elements.py
- tests/test_preprocess.py
- tests/test_utils.py
Resolves #412 
* adds `flake8` and `isort` to Linting in CI 
* adds `flake8` and `isort` to pre-commit
* runs `flake8` and `isort` on repo
* minor docstring cleanup
> add flake8 and isort to CI

- README.md
> proof README.md

- docs/_static/references.bib
> Make corrections in doc references

- tests/test_preprocess.py
> update skip message (#428)

- ci/envs/310-dev.yaml
- ci/envs/310-latest.yaml
- ci/envs/38-minimal.yaml
- ci/envs/39-latest.yaml
- environment.yml
- pyproject.toml
- requirements.txt
xref #437, #423
* pin `pandas==1.4.4` for most CI and set up environments
* pin `pandas>=0.230,<=1.4.4` for minimal environment
> Pin pandas versions prior to patch release

- ci/envs/310-dev.yaml
- ci/envs/310-latest.yaml
- ci/envs/38-minimal.yaml
- ci/envs/39-latest.yaml
- docs/install.rst
- environment.yml
- momepy/coins.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/intensity.py
- requirements.txt
- tests/test_elements.py
Resolves #435.
Also:
* [`UserWarning: Boolean Series key will be reindexed to match DataFrame index.`](https://github.com/pysal/momepy/actions/runs/3193784898/jobs/5212703675#step:6:265)
* [`DeprecationWarning: In the next version of libpysal, ...`](https://github.com/pysal/momepy/actions/runs/3193784898/jobs/5212703675#step:6:218)
> resolve iteritems() warnings and others

- readthedocs.yml
> Revert "retry building PDF from `readthedocs.yml`"

- ci/envs/310-latest.yaml
- ci/envs/311-dev.yaml
- ci/envs/311-latest.yaml
- ci/envs/38-minimal.yaml
- ci/envs/39-latest.yaml
- docs/install.rst
- environment.yml
- environments/Dockerfile
- momepy/coins.py
- momepy/dimension.py
- momepy/distribution.py
- momepy/elements.py
- momepy/intensity.py
- momepy/preprocessing.py
- momepy/shape.py
- momepy/tests/test_distribution.py
- momepy/tests/test_utils.py
- pyproject.toml
Replacing pygeos with shapely 2.0 and requiring it to run momepy. Shall we compatible with both pygeos and shapely backed in geopandas.
Closes #443
> REF: update for shapely 2.0

- momepy/coins.py
> DOC: add note to COINS re undirected graphs

- CHANGELOG.md
@jGaboardi I am including here only stuff that may interest end-user but the commit history contains more changes (refactoring, compatibility, CI, docs) that are not listed. Do we want to include those?
> RLS: add 0.6.0 changelog

- pyproject.toml
I have also removed the v0.6.0 tag and will try to do the release again once this is merged.
> RLS: fix PyPI long description

- momepy/coins.py
- momepy/diversity.py
- momepy/preprocessing.py
- momepy/utils.py
Only straightforward refactoring, no tests/functionality affected.
> REF: Simplify list and dict manipulation

- momepy/coins.py
- momepy/datasets/__init__.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/graph.py
- momepy/preprocessing.py
- momepy/shape.py
- momepy/tests/test_coins.py
- momepy/utils.py
Get rid of a few Python2 relics (e.g. explicit floats where integers are more appropriate) and make the code again a bit more compact and (hopefully) readable.
> Modernize code

- docs/conf.py
> remove ending copyright year in docs/conf.py

- momepy/tests/test_distribution.py
> TST: adapt tests to GEOS 3.12

- readthedocs.yml
> DOC: try fixing rtd

- .github/dependabot.yml
- .github/workflows/release_to_pypi.yml
- .github/workflows/tests.yaml
@jGaboardi how do I make dependabot to do this?
> GHA: update actions

- CHANGELOG.md
@jGaboardi I think that moving forward, we should adopt what the rest of the ecosystem is doing.
> RLS: add a changelog for 0.7.0

- momepy/functional/_distribution.py
- momepy/functional/tests/test_distribution.py
Functional version of alignment based on libpysal Graph. It is fast. 282x faster than the original.
```
61.6 ms ± 3.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
17.4 s ± 1.13 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
> ENH: add alignment to the new API

- .github/workflows/test_user_guide.yaml
- .github/workflows/tests.yaml
> GHA: move user guide testing to separate action, add workflow dispatch

- momepy/__init__.py
- momepy/functional/_intensity.py
- momepy/functional/tests/test_intensity.py
Refactoring courtyards calculation to fit with the functional API and to speed it up.
> functional courtyards calculation

- .github/release.yml
Update `release.yml` - troubleshoot [release action failure](https://github.com/pysal/momepy/actions/runs/9536783188/job/26284105614)
xref #543, #604 
***I'll self-merge once CI completes***
> Update `release.yml` - troubleshoot release action failure

- .pre-commit-config.yaml
update precommit to ruff docs dir --  xref #613
> update precommit to ruff docs dir

- momepy/functional/_dimension.py
- momepy/functional/_shape.py
Resolving failures seen in https://github.com/pysal/momepy/actions/runs/9599441901/job/26473188036?pr=622
> DOC: update docstrings to match numpy2 outputs

- docs/user_guide/combined/distribution.ipynb
- docs/user_guide/combined/intensity.ipynb
- docs/user_guide/getting_started.ipynb
- docs/user_guide/preprocessing/consolidate_intersections.ipynb
- docs/user_guide/simple/dimension.ipynb
- docs/user_guide/simple/shape.ipynb
- docs/user_guide/weights/diversity.ipynb
- docs/user_guide/weights/examples.ipynb
- docs/user_guide/weights/two.ipynb
- docs/user_guide/weights/weights_nb.ipynb
> DOC: update rest of the guide

- ci/envs/310-oldest.yaml
- environment.yml
- pyproject.toml
First checking if this actually fixes ci issues.
> CI: bump minimal requirements as per SPEC 0

- docs/_static/references.bib
> DOC: update face artifacts bibtex

- docs/conf.py
Act on https://about.readthedocs.com/blog/2024/07/addons-by-default/
> DOC: reflect changes in RTD

- docs/user_guide/graph/coins.ipynb
- docs/user_guide/preprocessing/consolidate_intersections.ipynb
More osmnx compatibility. The roundabout simplification notebook is now a bit broken but it runs. It will be deprecated anyway as all relevant stuff is going to move to the new simplification-focused project.
> DOC: more osmnx compat

- .github/workflows/mypy.yml
- .github/workflows/test_docstrings.yaml
- .github/workflows/test_user_guide.yaml
- .github/workflows/tests.yaml
- ci/envs/312-latest.yaml
- ci/envs/313-dev.yaml
- ci/envs/313-latest.yaml
- ci/envs/313-min.yaml
- docs/environment.yml
- environment.yml
> Add Python 3.13 to testing matrix

- momepy/shape.py
> TYP: fix type hints for new numpy
