pysal/momepy

- docs/api.rst
- momepy/intensity.py
- tests/test_intensity.py
Another (hopefully final) version of `node_density`. It no longer uses area, but length of reached network as a normalisation.
> ENH: node_density() based on nodes and length

- docs/api.rst
- momepy/elements.py
- momepy/utils.py
- tests/test_utils.py
I have found out that `multi2single` is just a duplication of Geopandas `explode`, so I have removed `multi2single`.
> MAINT: use geopandas explode() instead of multi2single (removed)

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/intensity.py
- momepy/utils.py
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_diversity.py
- tests/test_intensity.py
To simplify some methods and make them more explicit rather than implicit, majority of spatial weights now require being based on unique ID rather than on index. That allows using weights derived from tessellation directly on buildings and vice versa.
> API: use unique_ID column instead of index for spatial weights

- momepy/utils.py
In case of MultiPolygon geometry, `preprocess` may fail. This ensures that there is only Polygon geometry before running actual cleaning process.
> BUG: use explode() in the preprocess to avoid multigeometry

- README.md
- docs/index.rst
- docs/install.rst
- momepy/elements.py
- tests/test_elements.py
Remove `osmnx` dependency as it was used only once in tessellation. `_split_lines` is introduced instead. It is 10x faster than previous in division, but might be slower, but more precise in rtree selection of cells to cut.
> REF: remove osmnx dependency

- momepy/utils.py
- tests/test_utils.py
`snap_street_network_edge` now can snap to network only, tessellation edge is only optional. Later we might allow polygon as a limit instead of tessellation as well.
> ENH: allow snap of network only to itself

- .travis.yml
- ci/travis/37-mc.yaml
- ci/travis/37-pysal.yaml
- momepy/diversity.py
- tests/test_diversity.py
Within diversity module, allow `pysal` to be used for everything or separate `mapclassify` and `inequality` packages.
> ENH: Allow inequaliy and mapclassify to be used instead pysal and vv

- momepy/distribution.py
- momepy/utils.py
- tests/test_utils.py
Dissolve part of `snap_street_network_edge` might not be necessary as `limit` in `tessellation` is basically the same geometry we need. This PR allows passing it directly.
> ENH: snap_street_network_edge allow limit to avoid dissolve

- momepy/elements.py
- tests/test_elements.py
Allow (Multi)LineString input in `tessellation()`. Using street network as an input, one can generate proximity bands as in [Araldi & Fusco (2019)](https://journals.sagepub.com/doi/10.1177/2399808319832612).
> ENH: allow LineString input in tessellation() to get proximity bands

- momepy/intensity.py
- tests/test_intensity.py
For some reason, `W.neighbors` is a list if done using libpysal and array after export from networkx.
> BUG: node_density W.neighbors is array

- .travis.yml
- docs/api.rst
- momepy/graph.py
- tests/test_graph.py
Add Betweenness, straightness and global closeness centrality. Betweenness can be calculated on both nodes and edges. Rest on nodes, could be approximated on edges using `mean_nodes`.
> ENH: Multiple centrality assessment

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/intensity.py
- tests/test_dimension.py
- tests/test_diversity.py
- tests/test_intensity.py
Avoid `isin()` search where unique_id can be set as index. It provides significant performance gain.
> PERF: set unique_id as index for faster indexing

- momepy/graph.py
As all graphs generated by momepy are MultiGraphs, hence undirected, it is redundant to convert them to undirected for during `ego_graph`. It brings massive performance gain.
> PERF: ego_graph enhancement

- momepy/graph.py
- tests/test_graph.py
Straightness centrality of disconnected node currently raises error due to division by zero. Fixed.
> BUG: straightness centrality of disconnected node

- setup.py
Fixing following issue with installing under windows
```
ERROR: Command errored out with exit status 1:
command: 'C:\Users\wlb17212\AppData\Local\Continuum\anaconda3\envs\clustering\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wlb17212\\AppData\\Local\\Temp\\pip-req-build-2_cxjmyi\\setup.py'"'"'; __file__='"'"'C:\\Users\\wlb17212\\AppData\\Local\\Temp\\pip-req-build-2_cxjmyi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
cwd: C:\Users\wlb17212\AppData\Local\Temp\pip-req-build-2_cxjmyi\
Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File …
```
> BUG: encoding issue when installong from source on win

- momepy/graph.py
- tests/test_graph.py
Reimplemented ` local_betweenness_centrality` due to the performance issues for larger graphs. However, it cannot be normalised by the number of nodes within the whole graph, only by the number of nodes within subgraph. Normalisation by the whole graph can be done manually afterwards if needed.
> ENH: reimplement local_betweenness_centrality

- momepy/utils.py
- tests/test_utils.py
`_generate_dual()` within `gdf_to_nx()` expected index to be consecutive integer 0-n. That is no longer true and every kind of index should be okay.
> BUG: generating angular graph with non-default index

- momepy/dimension.py
- tests/test_shape.py
Fixes #108 
Move `_longest_axis` out of the class so it is accessible by other classes as well.  Added test to cover the import of `_longest_axis` in `CentroidCorners`.
> BUG: import of `_longest_axis`

- momepy/intensity.py
- tests/test_intensity.py
`AreaRatio` does not return resulting Series with the original index but reset one. That should be fixed now.
> BUG: AreaRatio resets index

- momepy/utils.py
- tests/test_utils.py
Even though the script itself works with GeoSeries, `network_false_nodes` did not support GeoSeries on input. Needed for future simplification of street network.
I have also formatted couple of docstrings along the way.
> ENH: network_false_nodes for GeoSeries

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/intensity.py
- momepy/utils.py
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_diversity.py
- tests/test_intensity.py
Probably closes #130 
Instead of throwing KeyError, feature which is not present in spatial weights now gets assigned np.nan. Should fixes cases when tessellation does not match buildings and similar.
> BUG: return np.nan if feature not in spatial_weights

- ci/travis/latest-mc.yaml
Temporarily pin libpysal to avoid failure on appveyor. libpysal 4.2.0 has encoding issue, which is being fixed in 4.2.1 but that is not on conda-forge yet.
> CI: pin libpysal

- momepy/intensity.py
- tests/test_intensity.py
`AreaRatio` now expects 1:1 match between covering and covered objects. This PR allows calculation worth multiple objects covering one (sharing object ID). 
Example could be Floor Area Ratio for block.
> ENH: AreaRatio for uneven number of features

- momepy/utils.py
- tests/test_utils.py
```py
net = net.explode()
mm.network_false_nodes(net)
```
This fails as `net` has MultiIndex. Fixed.
> BUG: network_false_nodes for multiindex

- CITATION.md
- LICENSE
- momepy/distribution.py
SharedWallsRatio might in some cases return values higher than 1, which is clear nonsense. It is caused by imprecise geometry, when intersection of two polygons results in a polygon, not line string as expected.
> ENH: vectorize SharedWallsRatio bit, note

- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/intensity.py
- momepy/shape.py
Minor refactor to use vectorised operations where possible. + pysal cleanup as double import is not needed with the latest pysal structure.
> REF: use vectorised operations

- momepy/dimension.py
- tests/test_dimension.py
This is a breaking change. If `mean=True`, resulting series is in `self.mean`, not `self.series` anymore. Sum is computed always.
> ENH: SegmentsLength allow sum and mean at the same run

- momepy/dimension.py
- tests/test_dimension.py
Allowing calculation of multiple averages (mean, median, mode) during the single run through gdf. It is a breaking change, as each of the will come with its own attribute `.mean`, `.median`, `.mode`, not in `.series`, which is just a copy of mean to keep default the same.
> ENH: multiple modes in AverageCharacter at the same run

- momepy/utils.py
- tests/test_utils.py
Fixes #142 
Make sure Z coordinate is supported in `gdf_to_nx` and `nx_to_gdf`. If LineString Z is passed to `gdf_to_nx`, Point Z is returned for nodes from `nx_to_gdf`.
> BUG: LineString Z support in nx_to_gdf

- ci/travis/37-pysal.yaml
- ci/travis/dev.yaml
- ci/travis/latest-mc.yaml
- momepy/utils.py
- tests/test_utils.py
Updated `nx_to_gdf()` to be compatible with osmnx graph. Now it should be possible to use osmnx graphs and other without expected structure directly within momepy and then save then using `nx_to_gdf()`. However, it is not recommended as `osmnx.save_load.graph_to_gdfs()` is tailored to OSM data, unlike `nx_to_gdf()` which expects already cleaned data.
> ENH: osmnx compatibility

- docs/conf.py
Use `sphinx.ext.linkcode`to link code directly to GH instead of `sphinx.ext.viewcode`.
> DOC: link code to GitHub

- momepy/diversity.py
- tests/test_diversity.py
Additional options for `Simpson` diversity character. Can be returned as Gini-Simpson (1-λ) or Inverse Simpson index (1/λ). For details see [wikipedia](https://en.wikipedia.org/wiki/Diversity_index).
> ENH: Gini-Simpson index, Inverse Simpson index

- momepy/intensity.py
- tests/test_intensity.py
In case of islands in spatial weights `Density` raised TypeError.
> BUG: Density TypeError for islands

- docs/api.rst
- momepy/__init__.py
- momepy/utils.py
- momepy/weights.py
- tests/test_weights.py
In some cases, `libpysal.weights.DistanceBand` may become too big for memory, e.g. for large thresholds. `momepy.DistanceBand` mimics its behaviour in terms of `.neighbors[key]` pattern used within momepy to compute neighbours only on demand to avoid memory issues. It is significantly slower method, but allows large thresholds which would otherwise not fit in memory. 
`momepy.DistanceBand` can be used within most momepy classes directly as spatial_weights instead of `libpysal.weights`.
> ENH: On demand DistanceBand spatial weights (neighbors)

- docs/api.rst
- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/graph.py
- momepy/intensity.py
- momepy/shape.py
- momepy/utils.py
- momepy/weights.py
- tests/test_shape.py
Fixed typos across docstrings.
Includes API change `Convexeity` -> `Convexity`. Since we're still in early dev phases, it is a hard breaking change without deprecation.
> API: Convexity typo, typos

- momepy/graph.py
- tests/test_graph.py
Functions of `momepy.graph` module can now return a value for a whole graph instead of subgraphs if `radius=None` (where applicable). Applies to:
- `meshedness`
- `cds_length`
- `mean_node_degree`
- `proportion`
- `cyclomatic`
- `edge_node_ratio`
- `gamma`
> ENH: support network analysis for full network

- ci/travis/37-pysal.yaml
- ci/travis/dev.yaml
- ci/travis/latest-mc.yaml
- environment.yml
All required dependencies are now on conda-forge, so no need to mix installation with pip.
> ENV: use only conda-forge

- docs/api.rst
- momepy/graph.py
- tests/test_graph.py
Deprecate `local_closeness_centrality`, `local_betweenness_centrality` and `local_straightness_centrality` and include the ability to compute local centrality to `closeness_centrality`, `betweenness_centrality` and `straightness_centrality`. Separate local options will be removed in 0.4.0.
> REF: consolidate MCA

- momepy/utils.py
- tests/test_utils.py
Fix CRS loss during `network_false_nodes`.
> BUG: preserve CRS in network_false_nodes

- momepy/distribution.py
Avoid one loop in `MeanInterbuildingDistance`. Vectorized pygeos distance operation is way faster than shapely loop. Further change can avoid double computation of distance (A-B and B-A can be done only once).
```
before           after         ratio
[05ca8623]       [c2855e7f]
<master>         <ibd_perf>
-         972±5ms          201±8ms     0.21  bench_distribution.TimeDistribution.time_MeanInterbuildingDistance
```
> REF: MeanInterbuildingDistance performance

- ci/travis/37-pysal.yaml
- momepy/__init__.py
- momepy/datasets/__init__.py
- momepy/dimension.py
- momepy/distribution.py
- momepy/elements.py
- momepy/weights.py
- tests/test_dimension.py
Refactor of `StreetProfile` to get better performance. There's still space for more work.
Benchmark:
```
before           after         ratio
[05ca8623]       [fece9f90]
<master>         <profile_perf~3>
-      3.17±0.01s       1.18±0.05s     0.37  bench_dimension.TimeDimension.time_StreetProfile
```
I've also fixed a bug I did not know about which sometimes picked incorrect height.
> REF: StreetProfile performance refactor

- momepy/utils.py
Continuation of #181, which apparently fixed the issue only for GeoPandas 0.8. This fixes it for 0.7 as well.
> BUG: crs lost with older geopandas

- momepy/elements.py
Some code cleanup and performance-focus refactoring in elements module. Most of it will affect only larger df. `get_node_id` also small:
```
374±8ms         99.4±5ms     0.27  bench_elements.TimeElements.time_get_node_id
```
> PERF: performance improvements in elements module

- benchmarks/bench_distribution.py
- momepy/distribution.py
- tests/test_distribution.py
Using `sindex.query_bulk` and fully vectorized operations. Requires geopandas 0.8+ as compat layer would be essentially reimplementing the same algorithm.
Bechmark from `185.296ms` to `37.5±1ms`.
> PERF: refactor SharedWallsRatio

- momepy/weights.py
- tests/test_utils.py
- tests/test_weights.py
Use part of adapted libpysal code directly. Will be changed once `libpysal.higher.order` returns <= k neighbors.
> PERF: perfomance enhancements in sw_high

- ci/travis/latest-mc.yaml
Black has a bug in the release 20, causing unfixable failure of style check. Pinning until the fix is released.
> CI: pin black

- CHANGELOG.md
- asv.conf.json
- benchmarks/bench_utils.py
- ci/travis/37-pysal.yaml
- ci/travis/dev.yaml
- ci/travis/latest-mc.yaml
- docs/api.rst
- environment.yml
- momepy/diversity.py
- momepy/utils.py
- setup.py
- tests/test_utils.py
Current `network_false_nodes` is being replaced by new vectorised function `remove_false_nodes`. This change adds `pygeos` as momepy's dependency.
The algorithm has been written as a part of [Urban Grammar AI research project](https://urbangrammarai.github.io).
> ENH: vectorised remove_false_nodes

- ci/envs/stable.yaml
- momepy/shape.py
- tests/test_diversity.py
- tests/test_shape.py
> ENH: capture MutliLineString in Linearity

- ci/envs/dev.yaml
- momepy/intensity.py
- momepy/preprocessing.py
- momepy/shape.py
Do not error on MultiPolygons in `Corners` and `CentroidCorners`. Untested but that is fine for now.
> ENH: support MultiPolygons

- momepy/dimension.py
- momepy/weights.py
- requirements.txt
- tests/test_distribution.py
- tests/test_weights.py
`DistanceBand` changed geometry of original gdf. Copy is needed here.
Plus some forgotten cleanup ahead of 0.4.1 bug fix release.
> BUG: don't change gdf in DistanceBand + cleanup

- momepy/dimension.py
When there is no intersection between parallel lines and buildings, some cases incorrectly resulted in `np.nan` instead of 0.
> BUG: resolve nans in StreetProfile

- tests/test_elements.py
GEOS3.9 returns geometries in a different order, therefore we cannot rely on `iloc` in tests
> TST: different order of geometries

- .github/workflows/tests.yaml
- .gitignore
- .pre-commit-config.yaml
- benchmarks/bench_intensity.py
- ci/envs/dev.yaml
- ci/envs/latest.yaml
- ci/envs/stable.yaml
- momepy/diversity.py
- momepy/elements.py
- momepy/preprocessing.py
- momepy/utils.py
- tests/test_diversity.py
- tests/test_intensity.py
- tests/test_utils.py
Changes the behaviour of node ID generated in `nx_to_gdf`to start from 0. 
That also fixes a bug in `NodeDensity`  which we didn't know we had :)
Fixes #273
> BUG: node ID doesn't match ID in weights

- momepy/diversity.py
- tests/test_diversity.py
> ENH: add dropna keyword to `Unique`

- momepy/utils.py
This PR fixes a minor typo in the [`util.gdf_to_nx()`](https://github.com/martinfleis/momepy/blob/1ddb296fe3e2f17db77c2b20df6f16f89943deca/momepy/utils.py#L167) docstring whereby the `length` keyword is used twice: once correctly describing `length` and once incorrectly describing `angle`.
> small typo in gdf_to_nx

- momepy/elements.py
- tests/test_elements.py
Ensures that generated enclosures are fully within a `limit` (when provided) by calling `geopandas.clip`.
@matthew-law can you test this patch on your data? I'd also like to know what is the performance hit of doing this (it may be significant). I may add a keyword to controlm whether we should try to clip or not.
closes #287, closes #270
> BUG: properly clip enclosures by limit

- docs/user_guide/graph/coins.ipynb
- docs/user_guide/graph/convert.ipynb
- docs/user_guide/graph/network.ipynb
This PR cleans up the grammar in the notebooks comprising street network analysis functionality in the user guide.
> DOC: edit/proof street network analysis notebooks

- momepy/elements.py
Fixes #295 
@matthew-law You were right, in my test, the single-core implementation was actually a bit faster than parallel. This seems to fix the problem. 
I am a bit worried though. I used `bag` initially and then when moving the code to momepy, I have switched to dask.Series. I just don't remember why. Can you try this version on your data? My assumption is that it should go from 30 minutes to about 5.
> PERF: use dask.bag in Tessellation

- README.md
- asv.conf.json
- docs/conf.py
- docs/contributing.rst
- docs/index.rst
- docs/install.rst
- environments/Readme.md
Fixing links from `martinfleis` -> `pysal` and trying to figure out which bits of CI work and which do not.
Closes #301
> Fix links after the transfer under pysal org

- momepy/diversity.py
- tests/test_diversity.py
I realised that the `simpson_diversity` helper function can be much simpler than it was. Also, `categories` keyword made no difference to the calculation so I dropped it from the helper. It is still part of the signature of `Simpson` though, to avoid any breakage. I assume that it will get cleaned with the API revamp (#308).
> REF: simplify calculation of Simpson diversity

- .github/workflows/tests.yaml
- ci/envs/310-dev.yaml
- ci/envs/310-latest.yaml
- ci/envs/37-minimal.yaml
- ci/envs/38-latest.yaml
- ci/envs/39-latest.yaml
- momepy/__init__.py
- momepy/coins.py
- momepy/dimension.py
- momepy/elements.py
- momepy/preprocessing.py
- momepy/utils.py
- requirements.txt
- setup.py
- tests/test_coins.py
- tests/test_dimension.py
- tests/test_distribution.py
- tests/test_diversity.py
- tests/test_elements.py
- tests/test_graph.py
- tests/test_intensity.py
- tests/test_preprocess.py
- tests/test_shape.py
- tests/test_utils.py
- tests/test_weights.py
`LooseVersion` is deprecated. The warning recommends replacing it with `packaging.version`, which is exactly what I am doing here. Apart from that, I have also ran `isort` and temporarily turned off `fail-fast` in CI, while there's that GeoPandas regression.
> MAINT: replace LooseVersion with packaging.version

- momepy/distribution.py
Simplification (and likely a speedup) of computation of a deviation from cardinal directions from an azimuth.
> REF: simplify orientation calculation

- tests/test_elements.py
- tests/test_utils.py
We have two tests failiung due to https://github.com/geopandas/geopandas/issues/2282 . Skipping to avoid CI failures. It will be fixed in geopandas ahead of 0.11.
> TST: skip to avoid geopandas regression

- .pre-commit-config.yaml
- momepy/elements.py
- momepy/shape.py
- momepy/weights.py
- tests/test_elements.py
- tests/test_utils.py
Fixing the case when one block is fully within the exterior of the other. It currently creates overlapping blocks, this should fix it.
> BUG: fix issue with blocks within another blocks

- CHANGELOG.md
I mistakenly committed first commit of a changelog directly to main. This adds the other bug fix. I want to release today to resolve https://github.com/martinfleis/numerical-taxonomy-paper/issues/2 that has been coming up for some time but until yesterday I wasn't able to reproduce it. It should also mostly resolve https://github.com/pysal/momepy/discussions/339
> RLS: 0.5.3 changelog

- momepy/utils.py
- tests/test_utils.py
Some road sections can be passed in a bidirectional manner. Either the user has to preprocess his GeoDataFrame (to add an additional LineString in a opposite direction) or we can introduce a function where based on a boolean column, a user can specify which linestrings (roads) are `oneway` or not:
This functionality is helpful for path finding applications in directed graphs, where the same road can be traversed in the opposite direction.
> ENH: support bi-directional roads in gdf_to_nx

- README.md
- docs/index.rst
I suggest removing an option to contact us via dev@momepy.org email. It currently goes only to my email, is rarely used and practically everything that goes there should be either an issue or a discussion here. There's no need to keep any of it in a private email conversation.
> DOC: remove dev mail

- momepy/preprocessing.py
- tests/test_preprocess.py
When there is nothing to fix, `remove_false_nodes` just does nothing but it should rather return the original df.
> BUG: return itself when no change possible in remove_false_nodes

- momepy/coins.py
Fix bug initially reported by @gregmaya [here](https://github.com/pysal/momepy/discussions/361#discussioncomment-3365328). 
The issue is that ```coins``` depends on ```gdfs``` with a unique index. However, this will not always be guaranteed. With the modification,  a unique index is created by ```coins``` that is used to build back ```coins.stroke_attribute()```
There were some failing tests on my end but unrelated to ```coins```.
-Andres
> BUG: make coins independent of gdf index

- momepy/utils.py
- tests/test_utils.py
First of all: Thanks for momepy, a great tool for spatial analysis and processing. 
The gdp_to_nx function is pretty nice to convert data, previous read from a shape file into a geopanda frame, to a network graph. 
But from my point of view it makes only sense if the given data consist of LineStrings only, because a point will be converted to an edge with the same start and endpoint. The endpoints will not inherit any attributes from the original data.
I added a warning to inform the user about the pitfall, if any datum has a geometry != Linestring
-- Changes:
Added check and warning in function
Added minimal test if warning is thrown
kind regards
> Added warning for gdp_to_nx if geometries are not LineStrings

- momepy/elements.py
Replacing pandas `append` by `concat` to avoid the FutureWarning.
> REF: remove deprecated pandas append

- docs/requirements.txt
This should fix the docs build. The issue is caused by https://github.com/pydata/pydata-sphinx-theme/pull/911 and have already been fixed in upstream in https://github.com/pydata/pydata-sphinx-theme/pull/915, so temporarily pinning until the next release is out.
> DOC: temporarily pin theme

- docs/conf.py
This PR bumps the copyright year in `conf.py` to 2022.
> bump copyright year

- .github/workflows/release_to_pypi.yml
The GHA is complaining over at geopandas/xyzservices where we have the same config:
> [Build and publish xyzservices to PyPI: # >> PyPA publish to PyPI GHA: UNSUPPORTED GITHUB ACTION VERSION <<#L1](https://github.com/geopandas/xyzservices/commit/e6315d8026569fa7626a265ae9d89642d4a75aae#annotation_4652189477)
You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.
this should fix that
> GHA: update PyPI release action

- momepy/diversity.py
- tests/test_diversity.py
> resolves bug in Percentiles append.

- readthedocs.yml
This PR reverts 3dd803b. We may also want to try update the Python version with `readthedocs.yml`.
xref #294
> retry building PDF from `readthedocs.yml`

- .github/workflows/tests.yaml
- requirements.txt
This PR follows up with #467
* removes `--cov-config .coveragerc` from `tests.yml` (there's no longer a `.coveragerc` file`)
* removes the redundant `requirements.txt`, which now reside within [`pyproject.toml`](https://github.com/pysal/momepy/blob/b4a415677fe3b2c0f9ce5f9700833cb88fae583f/pyproject.toml#L36-L44).
https://github.com/pysal/momepy/blob/b4a415677fe3b2c0f9ce5f9700833cb88fae583f/pyproject.toml#L36-L44
*
> remove redundant `requirements.txt`

- momepy/tests/test_intensity.py
We have a CI in dev env. The result is correct but the order of rows in blocks is coming different from some geopandas operation. 
We don't really care about that so I am just replacing the test with something a bit more robust.
I also noticed that the whole `Blocks` algo would deserve a bit of refactoring but that is a problem for another time.
> TST: fix a flaky test in Count

- momepy/elements.py
- momepy/tests/test_elements.py
> support strings in `elements.get_node_id()`

- .github/workflows/tests.yaml
Closes #529 
Using the model from dask/dask. Not sure how to test this :D.
> CI: fix action creating issue from pytest

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- momepy/preprocessing.py
- momepy/shape.py
- momepy/tests/test_elements.py
- momepy/utils.py
- pyproject.toml
Fixing the issue in dev CI (that is actually a regression on dev GeoPandas but we can avoid it) and removing the xarray-contrib/issue-from-pytest-log action that does not work.
edit: also resolves #531
edit2: adopt ruff-format
> CI/TST: fix test, rm log action, ruff-format

- .github/workflows/mypy.yml
- momepy/functional/_dimension.py
I suppose this is how typing in momepy can look? Is that an improvement? Shall we do it?
> TYP: add type hints to functional._dimension

- .github/workflows/tests.yaml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> CI: test on Apple Silicon

- momepy/__init__.py
- momepy/functional/_dimension.py
- momepy/functional/_shape.py
- momepy/functional/tests/test_shape.py
Completely refactored `shape.py`. This was probably the easiest of them all. 
Performance comparison on data covering whole Prague:
|                              |        old (s) |         new (s) |      comparison |
|:-----------------------------|-----------:|------------:|----------:|
| form_factor                  |  0.0177744 |  0.0144857  | 0.814978  |
| fractal_dimension            |  0.011218  |  0.00919267 | 0.81946   |
| facade_ratio                 |  0.010366  |  0.00798157 | 0.769973  |
| circular_compactness         |  3.75679   |  1.46005    | 0.388644  |
| square_compactness           |  0.0107254 |  0.0082286  | 0.767205  |
| convexity                    |  0.491798  |  0.496109   | 1.00876   |
| courtyard_index              |  0.141855  |  0.141236   | 0.99564   |
| …
> REF: functional implementation of shape module

- momepy/__init__.py
- momepy/functional/_distribution.py
- momepy/functional/tests/test_distribution.py
Orientation:
```
```
Shared walls:
```
```
This is slower but it does not cause erroneous results coming from overlapping polygons.
> ENH: add orientation and shared_walls functional versions

- momepy/functional/_distribution.py
- momepy/functional/tests/test_distribution.py
Only a boring 10x speedup here 😃 
```
15.3 s ± 362 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.5 s ± 4.38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
It currently prints warnings but those shall be solved by https://github.com/geopandas/geopandas/issues/1832.
> ENH: neighbor_distance using Graph and new API

- ci/envs/310-latest.yaml
- ci/envs/310-oldest.yaml
- ci/envs/311-latest.yaml
- ci/envs/312-dev.yaml
- ci/envs/312-latest.yaml
- docs/install.rst
- environment.yml
- momepy/functional/_distribution.py
- momepy/functional/tests/test_distribution.py
- momepy/functional/tests/test_shape.py
- pyproject.toml
Gosh I spent way too much time on this...
mean_interbuilding_distance:
```
35s new
57s old
```
Given my first attempt took 5mins, I call this a victory. 
building_adjacency:
```
old: 251 ms ± 14.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
new: 422 ms ± 12.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
of which 330 ms is `assign_self_weight` which will be used in other functions so I'm wondering if it is worth adding a keyword `self_weighted=True` to skip this. In practice it is nearly negligible difference though...
These two functions also quite significantly change the API compared to the original. @jGaboardi can you give it a thought whether it makes sense in this way? I think it does and it is more flexible than before but it is different.
> ENH: mean_interbuilding_distance and building_adjacency

- momepy/functional/_distribution.py
- momepy/functional/tests/test_distribution.py
- pyproject.toml
Easy one this time. Hard to time, as `cardinalities` are cached.
```
```
Faster esp. if other function before called cardinalities.
> ENH: add neighbors

- momepy/__init__.py
- momepy/functional/_elements.py
- momepy/functional/tests/test_elements.py
WIP but the code works already.
For morphological tessellation:
```
new: 8min 43s
old: 27min 8s
```
For enclosed tessellation:
```
```
> ENH: refactor tessellation

- momepy/functional/_distribution.py
- momepy/functional/_elements.py
- momepy/functional/tests/test_distribution.py
- momepy/functional/tests/test_elements.py
I love how streamlined these things are now compared to the original :).
> ENH: street_alignment and get_nearest_street

- momepy/functional/_distribution.py
- momepy/functional/_elements.py
Series, GeoSeries and GeoDataFrame are imported directly. It was mostly like this but it was inconsistent.
> TYP: consistency in typing

- momepy/dimension.py
This is more a discussion than actual PR. I went through `dimension.py` and thought about the future of all of the classes we have there. There are two main questions
1. Do we keep these as thin wrappers around `Graph.lag` or point directly to lag?
2. What should be moved to libpysal and how?
> notes on plans with the rest of dimension classes

- momepy/coins.py
- momepy/dimension.py
- momepy/elements.py
- momepy/functional/_elements.py
- momepy/functional/tests/test_elements.py
- momepy/intensity.py
- momepy/preprocessing.py
- momepy/tests/test_dimension.py
- momepy/tests/test_distribution.py
- momepy/tests/test_diversity.py
- momepy/tests/test_elements.py
- momepy/tests/test_graph.py
- momepy/tests/test_intensity.py
- momepy/tests/test_preprocess.py
- momepy/tests/test_shape.py
- momepy/tests/test_utils.py
- momepy/tests/test_weights.py
- momepy/utils.py
- momepy/weights.py
- pyproject.toml
I wanted to primarily cleanup warnings from our CI. So some changes related to that, some changes related to compatibility (FutureWarning removal), plus linting of tests which was for some reason disabled.
> MAINT: compatibility, warning cleanup, test lint

- ci/envs/310-oldest.yaml
- momepy/functional/_diversity.py
- momepy/functional/tests/conftest.py
- momepy/functional/tests/test_diversity.py
a new functional version of the mm.Reached function. It calculates several statistics at once similar to mm.describe(
> functional reached calculations

- momepy/elements.py
- momepy/functional/_elements.py
- momepy/functional/tests/test_elements.py
Making use of Gabriel graph to determine the buffer of each building when defining the study area.
See this [notebook](https://github.com/uscuni/urban_taxonomy/blob/main/code/adaptive_buffer.ipynb) for explanation.
It requires libpysal main to properly work...
> ENH: adaptive buffer as a tessellation limit

- ci/envs/310-latest.yaml
- ci/envs/310-oldest.yaml
- ci/envs/311-latest.yaml
- ci/envs/312-dev.yaml
- ci/envs/312-latest.yaml
- ci/envs/312-min.yaml
- docs/install.rst
- environment.yml
- pyproject.toml
We need to depend heavily on `Graph.describe()`, so better pin 4.11 than raise a ton of ImportErrors. SPEC0 is imho irrelevant within the fed.
> DEP: bump libpysal minimum to 4.11

- momepy/functional/_dimension.py
- momepy/functional/tests/test_dimension.py
funcitonal street profile. The equivalence tests have rtol between .01 and 1, to account for the different segmentation strategies.
> Street profile

- momepy/functional/_elements.py
We have noticed a nasty issue with the contiguity of enclosed tessellation caused by floating point imprecision within GEOS. Spent some time trying to fix it but I don't think it is possible with the current version of GEOS / shapely. For our use case, there is a solution, so making a note in the docstring.
Repr of the issue:
```py
import geopandas as gpd
import momepy
streets = gpd.read_file(momepy.datasets.get_path("bubenec"), layer="streets")
buildings = gpd.read_file(momepy.datasets.get_path("bubenec"), layer="buildings")
enclosures = momepy.enclosures(streets, limit=momepy.buffered_limit(buildings, buffer=50))
tess = momepy.enclosed_tessellation(buildings, enclosures)
tess.union_all()
```
The lines shown in the interior are actual gaps in contiguity when building the graph:
```py …
```
> DOC: note on a precision issue in enclosed_tessellation

- docs/user_guide/combined/distribution.ipynb
- docs/user_guide/combined/intensity.ipynb
- docs/user_guide/getting_started.ipynb
- docs/user_guide/simple/dimension.ipynb
- docs/user_guide/simple/shape.ipynb
- docs/user_guide/weights/diversity.ipynb
- docs/user_guide/weights/examples.ipynb
- docs/user_guide/weights/two.ipynb
- docs/user_guide/weights/weights_nb.ipynb
- momepy/functional/_elements.py
- momepy/functional/tests/test_elements.py
Normally, you will want to use tessellation as a gdf, so easier to return it as such and avoid all those `to_frame` calls. This also makes the output type consistent with `enclosed_tessellation`.
> API: return morphological tessellation as a GeoDataFrame

- docs/user_guide/elements/blocks.ipynb
- docs/user_guide/elements/enclosed.ipynb
- docs/user_guide/elements/tessellation.ipynb
- docs/user_guide/graph/convert.ipynb
- docs/user_guide/graph/network.ipynb
- docs/user_guide/simple/dimension.ipynb
- docs/user_guide/simple/shape.ipynb
- docs/user_guide/weights/diversity.ipynb
- docs/user_guide/weights/examples.ipynb
@jGaboardi any idea why it was not picked up by pre-commit?
> DOC: ruff user guide

- momepy/functional/_dimension.py
- momepy/functional/_distribution.py
- momepy/functional/_elements.py
- momepy/functional/_shape.py
> DOC: remaining examples in the new API

- docs/legacy_api.rst
- momepy/tests/test_utils.py
- momepy/utils.py
This introduces an environment variable `ALLOW_LEGACY_MOMEPY` which, when set to True, silences all the deprecation warnings about the legacy API.
I am open to a discussion about the name of the variable but I'd say anything without a possibility of conflicts is good enough.
> API: allow silencing of FutureWarnings from legacy API

- .github/workflows/tests.yaml
- momepy/dimension.py
- momepy/distribution.py
- momepy/diversity.py
- momepy/elements.py
- momepy/intensity.py
- momepy/shape.py
- momepy/tests/test_dimension.py
- momepy/tests/test_intensity.py
- momepy/tests/test_utils.py
- momepy/weights.py
Closes #612 
Adds decorators and custom warnings when decorator does not fit to remaining classes.
The only missing is `NeighboringStreetOrientationDeviation`. @u3ks what are we doing about that one?
@u3ks also, can you review this if I'm pointing to correct things?
> API: deprecate legacy API in favour of Graph-based functional implementation

- momepy/graph.py
> TYP: add type hints to the graph module

- docs/user_guide/intro.rst
- docs/user_guide/migration.ipynb
> DOC: add migration guide to new API

- momepy/coins.py
- momepy/tests/test_coins.py
This adds flow mode of continuity which ensures that there's only a one stroke group per LineString and does not cause breakage when dealing with stroke attributes rather than stroke geometries.
> ENH: add flow mode to COINS

- momepy/preprocessing.py
- momepy/tests/test_preprocess.py
This addition ensures that closed loops have their start/end point attached to the rest of the network.
> BUG: fix ordering of closed loops in remove_false_nodes

- momepy/coins.py
- momepy/tests/test_coins.py
Adding the option to pull out the information about the ends of stroke groups.
> ENH: allow extraction of coins ends in COINS.stroke_attribute

- momepy/functional/_distribution.py
- momepy/functional/tests/test_distribution.py
Add a keyword to the existing shared_walls function, in order to approximate the result when the input geometry has tolopogical and floating point issues.
> Approximate shared walls

- momepy/functional/_dimension.py
- momepy/functional/_intensity.py
- momepy/functional/tests/test_dimension.py
- momepy/functional/tests/test_intensity.py
Expose the buffer variable for perimeter_walls and courtyards
> expose buffer variable

- momepy/coins.py
The check for overlapping lines we have added in 0.8 is a bit annoying as in most cases, it is a single stroke group that is affected. So I am changing that to a warning and using 0 as an angle.
This also means that some minor issues caused by the simplification pipeline will not cause the whole thing to break on this error.
cc @anastassiavybornova
> let COINS run even if there's overlapping geometry

- momepy/preprocessing.py
- momepy/tests/test_preprocess.py
* This PR resolves #657 
* Open to suggests for a better error message.
* [CI failure](https://github.com/pysal/momepy/actions/runs/11465621653/job/31904469874) unrelated to this PR
> ENH: do not fail with 3d nodes - `preprocess.remove_false_nodes()`

- momepy/preprocessing.py
- momepy/tests/test_preprocess.py
This PR:
* resolves #664 
* resolves #665
> handling edge cases in `preprocessing.FaceArtifacts`

- momepy/streetscape.py
- momepy/tests/test_streetscape.py
This allows linking the data back to building and plot geometry if needed. Using sets as there can be more than one hit.
> ENH: retain index of buildings and plots intersecting sightlines

- momepy/streetscape.py
This fixes an issue in Streetscape that may occasionally happen when there is a single hit per point. Not sure why the tests did not flag this as we do have such occasions but this at least fixes it on one real world sample I got.
> BUG: fix extraction of ids if there is only a single hit when retrieving point level data in Streetscape

- momepy/streetscape.py
This should not happen as we filter in sindex query first. Yet, it does.
> BUG: fix corner case of empty intersection in streetscape

- momepy/streetscape.py
> Get mean of actual values (do not imply missing == 0) in Streetscape

- momepy/coins.py
This PR fixes a small warning typo in `coins.py`.
> fix small warning typo in `coins.py`

- readthedocs.yml
I think I changed the tessellation guide which broke the link.
> DOC: fix the image link in lcustering example

- momepy/functional/_elements.py
What it says. Sometimes it is useful to tweak grid_size to avoid some precision issues.
> ENH: allow passing kwargs to voronoi_frames in tessellation

- momepy/tests/test_dimension.py
- momepy/tests/test_intensity.py
These tests failed on Debian i386, probably due to x87 excess precision: https://bugs.debian.org/1103140
> MAINT: add more pytest.approx calls
